### ISSUE TITLE
09.07.00 Release Notes

### ISSUE THREAD

**Issue by EPTamminga** [dnnsoftware/Language-Pack-NL-NL#114]
## Release notes voor het nl-NL Taalpakket

Allereerst bedanken we iedereen in de community voor de Pull Requests die zijn aangeleverd en/of voor het melden van problemen. We hebben daar dankbaar gebruik gemaakt bij het samenstellen van het nl-NL taalpakket voor deze release van DNNPlatform. Word ook actief community member en draag bij aan DNNPlatform voor het Nederlandse taalgebied.

### Language Pack nl-NL versie 09.07.00

Belangrijkste verbeteringen in deze release van het nl-NL taalpakket:

*   Toevoegen van nieuwe DNN 09.07.00 tekstelementen
*   Verbeteren van de teksten van de registratie, profiel, paginabeheer

Bijdragen voor deze update kwamen van: [@schotman](https://github.com/schotman); [@EPTamminga](https://github.com/EPTamminga)

## Release notes for the nl-NL Language pack (ENGLISH VERSION)

First of all, we thank everyone in the community for the Pull Requests that have been submitted and/or for reporting issues. We made grateful use of this when creating the update of the nl-NL language package for this release of DNNPlatform. Become an active community member as well and contribute to DNNPlatform for the Dutch language area.

### Language Pack nl-NL version 09.07.00

Changes in this release of the nl-NL language pack:

*   New DNN 09.07.00 text elements added
*   Improvement of text elements of registration, user profile, page management

Contributions for this update from: [@schotman](https://github.com/schotman); [@EPTamminga](https://github.com/EPTamminga)

**Comment by valadas** [comment]
Excellent, I put that in the release
