### ISSUE TITLE
Creating a new Default none en-US site has missing text

### ISSUE THREAD

**Issue by EPTamminga** [dnnsoftware/Language-Pack-NL-NL#132]
## Description of bug
Creating a new Default none en-US site has missing text on the home page

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Create a new DNN960 site in nl-NL (Dutch)
2. See error

## Current behavior
Text placeholders

## Expected behavior
Normal nl-NL text

## Screenshots
![image](https://user-images.githubusercontent.com/5859855/80809892-ed566580-8bc2-11ea-9df2-786d4d61320c.png)

## Error information
-

## Additional context
-

## Affected version

* [x] 9.6.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer 11
* [x] Microsoft Edge (Classic)
* [x] Microsoft Edge Chromium

**Comment by valadas** [comment]
I transferred the issue here since it need to be done in language packs.

**Comment by EPTamminga** [comment]
Not an issue anymore
