### ISSUE TITLE
Accidental Fork, sorry :-(

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Language-Pack-NL-NL#137]
Ok, I think I just made a mistake and forked this repo to 
https://github.com/DNNCommunity/Language-Pack-NL-NL

But I don't seem to have the rights to remove that fork.
Can someone with the appropiate rights do that please?

@valadas @david-poindexter ? :-)

**Comment by valadas** [comment]
Yeah, let me try that...

**Comment by valadas** [comment]
Done, thanks for warning us.

**Comment by Timo-Breumelhof** [comment]
@valadas thank you
