### ISSUE TITLE
ResourceManager translation files not included in version 9.10

### ISSUE THREAD

**Issue by aspelt** [dnnsoftware/Language-Pack-NL-NL#158]
In the ZIP file the Translated ResourceManager files are not included.

**Comment by valadas** [comment]
It looks fine to me:
![image](https://user-images.githubusercontent.com/6371568/133741592-0d0aff2a-bf1a-4fa1-9eba-693f3a681a90.png)

**Comment by EPTamminga** [comment]
The DNN nl-NL 09.10.00 does contain the translation for de ResourceManager.

Issue can be closed

**Comment by aspelt** [comment]
Sorry! I see it.

**Comment by EPTamminga** [comment]
You are correct: it was in the zip, but not in the manifest, so the files did not install.
Aangepast in 09.10.01
