### ISSUE TITLE
Exceptions text corrections

### ISSUE THREAD

**Issue by EPTamminga** [dnnsoftware/Language-Pack-NL-NL#33]
Improving translations

**Comment by aspelt** [comment]
Ik will take a look at the file. 
Question: Do we speak about 'portaal' in Ducth or do we use 'portal'.

**Comment by EPTamminga** [comment]
@aspelt I have some discussion with @donker. 
We want to set-up a list of standard terms for translation. 
Probably not portal or portaal, but site.
