### ISSUE TITLE
admin\Security\App_LocalResources

### ISSUE THREAD

**Issue by trouble2** [dnnsoftware/Language-Pack-NL-NL#41]
In DNNCE_nl-NL.dnn staat ergens:

<languageFile>
     <path>admin\Security\App_LocalResources</path>
     <name>dataconsent.ascx.nl-NL.resx</name>
</languageFile>

Volgens mij moet dat weg...

**Comment by EPTamminga** [comment]
Waar zie je dat? 

Bij mij staat er: 

`<languageFile>`
`	<path>admin\Security\App_LocalResources</path>`
`	<name>dataconsent.ascx.nl-NL.resx</name>`
`</languageFile>`

Het enige dat anders is het gebruik van HOOFD- en kleine letters.
Die resx file is nieuw en dus heb ik het opgenomen

**Comment by trouble2** [comment]
Ok, ik denk dat het:
\DesktopModules\Admin\Security\App_LocalResources
ipv.
\Admin\Security\App_LocalResources

moet zijn dan...

**Comment by EPTamminga** [comment]
OK, sharp spot. Ik corrigeer het

**Comment by trouble2** [comment]
Ik zie trouwens ook dat:
DesktopModules\Connectors\GoogleAnalytics\App_LocalResources\SharedResources.nl-NL.resx
mogelijk ontbreekt...

**Comment by EPTamminga** [comment]
Ik zie hem wel in de repo staan:

`
https://github.com/dnnsoftware/Language-Pack-NL-NL/blob/develop/Resources/DesktopModules/Connectors/GoogleAnalytics/App_LocalResources/sharedresources.nl-NL.resx
` 

en ook in de DNN manifest
