### ISSUE TITLE
Change U/Uw into Jij/Jouw in admin\

### ISSUE THREAD

**Issue by EPTamminga** [dnnsoftware/Language-Pack-NL-NL#46]
First part

**Comment by aspelt** [comment]
@EPTamminga Ik wil hier (graag) een bijdrage aan leveren. Zou graag even contact hebben over hoe het beste aan te vliegen.

**Comment by EPTamminga** [comment]
Mooi!

Ik heb verschillende issues gemaakt om de folders op te delen. We moeten even wachten met PR's aanleveren totdat 961 nl-NL pack in release staat. Maar we kunnen wel lokaal werken.

Mijn idee is de opsplitsing. 

Je pakt 1 van de 7 issues (folders) beet, Ze je naam in een comment van de issue en gaat dan met alle subfolders en files in die folder aan de slag. Na gereed maak je 1 PR, dus straks hebben we 7 PR's.
Ik heb geen rechten hier om "Assignees" te doen, dus daarom je naam in de comment, dan weten we van elkaar of er iemand mee bezig is.

Ik denk dat de Desktopmodules\ het omvangrijkste is. Eventueel splitsen we die dan in een PR per subfolder.

Zo werkend hebben we geen "last" van elkaar.

**Comment by aspelt** [comment]
Prima! Ik ben nog even aan het stoeien met de Translator.

**Comment by EPTamminga** [comment]
@aspelt Ik begin "achteraan"

**Comment by EPTamminga** [comment]
Solved by PR #61
